# Generated by Django 4.0.3 on 2022-03-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='content',
        ),
    ]
