# Generated by Django 4.0.3 on 2022-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('конкурс', models.CharField(max_length=255)),
                ('результат', models.CharField(max_length=255)),
                ('дата', models.CharField(max_length=255)),
                ('место_провидения', models.CharField(max_length=255)),
            ],
        ),
    ]
