# Generated by Django 4.0.3 on 2022-03-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('picture', models.ImageField(default='default value', upload_to='')),
                ('author', models.CharField(default='anonymous', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default=' DataFlair Django tutorial')),
            ],
        ),
    ]
