# Generated by Django 4.0.3 on 2022-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_wiki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='content',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='picture',
        ),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='describe',
            field=models.TextField(default=' DataFlair Django tutorial'),
        ),
        migrations.AddField(
            model_name='posts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='posts',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
