# Generated by Django 4.0.3 on 2022-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_wiki_author_remove_wiki_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wiki',
        ),
    ]
