# Generated by Django 4.0.3 on 2022-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_wiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='дата',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='table',
            name='конкурс',
        ),
        migrations.RemoveField(
            model_name='table',
            name='место_провидения',
        ),
        migrations.RemoveField(
            model_name='table',
            name='результат',
        ),
        migrations.AddField(
            model_name='table',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='table',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
